name: Docker Image Release

on:
  release:
    types: [published] # triggers when a new GitHub Release is published

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # needed to push to GHCR
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build . \
            -f docker/php/Dockerfile \
            -t ghcr.io/${REPO_OWNER}/bandbinder:latest \
            -t ghcr.io/${REPO_OWNER}/bandbinder:${{ github.event.release.tag_name }}

      - name: Push Docker image
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${REPO_OWNER}/bandbinder:latest
          docker push ghcr.io/${REPO_OWNER}/bandbinder:${{ github.event.release.tag_name }}
